name: Render Deployment Status

on:
  push:
    branches:
      - main  # Triggers on pushes to the 'main' branch

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify Deployment Success
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"state": "success", "description": "Deployed to Render", "environment": "production"}' \
            https://api.github.com/repos/Sharkytony/Used-Car-Price-Prediction-Project/deployments
